# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-21 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190821_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRK', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
